-- AlterTable
ALTER TABLE "user" ALTER COLUMN "created_at" DROP NOT NULL,
ALTER COLUMN "updated_at" DROP NOT NULL,
ALTER COLUMN "is_active" DROP NOT NULL,
ALTER COLUMN "is_active" SET DEFAULT false,
ALTER COLUMN "is_admin" DROP NOT NULL,
ALTER COLUMN "is_deleted" DROP NOT NULL,
ALTER COLUMN "is_deleted" SET DEFAULT false;
